server:
  port: 8001
# spring相关配置
spring:
  application:
    name: microservice-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    druid:
      test-while-idle: true
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
# mybatis配置
mybatis:
  mapperLocations: classpath:dao/*.xml
  type-aliases-package: com.buba.springcloud.pojo
#eureka:
#  client:
#    #表示是否将自己注册进eureka  默认为true
#    register-with-eureka: true
#    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
#    fetch-registry: true
#    service-url:
#      #单机配置
#      defaultZone: http://localhost:7001/eureka
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 这里即便只写一个7001，7002也能够识别该服务
  instance:
    #服务名称修改
    instance-id: payment8001
    #访问路径可以显示ip地址
    prefer-ip-address: true
